const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Skin Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      images: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'A wonderful shirt',
    },
    {
      _id: '2',
      name: 'Puma Skin Shirt',
      slug: 'puma-slim-shirt',
      category: 'Shirts',
      images: '/images/p2.jpg',
      price: 120,
      countInStock: 0,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'A wonderful shirt',
    },
    {
      _id: '3',
      name: 'Adidas Skin Shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      images: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'A wonderful shirt',
    },
    {
      _id: '4',
      name: 'UnderArmor Skin Shirt',
      slug: 'underarmor-slim-shirt',
      category: 'Shirts',
      images: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'UnderArmour',
      rating: 4.5,
      numReviews: 10,
      description: 'A wonderful shirt',
    },
  ],
};

export default data;
